apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: europe-west4-docker.pkg.dev/qwiklabs-gcp-02-9d611893f204/my-repository/sample-app-dev:v1.0
        ports:
        - containerPort: 8080
